# This workflow will build and test a Java project with Maven.
# It runs automatically on any push or pull request to the 'main' branch.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository's code so the workflow can access it.
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the correct version of Java (JDK 21 for your project).
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies to speed up future builds.
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Run the Maven build command.
    # This will compile the code, run tests, and package the application.
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
