# This workflow will build, test, and save the final .jar file.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    # --- ADD THIS NEW STEP ---
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # The name of the artifact to be uploaded. This will be the name of the .zip file.
        name: GymTracker-Jar
        # The path to the file(s) to upload.
        # This will find the .jar file inside the target directory.
        path: target/*.jar
